### ISSUE TITLE
有没有在Linux上用的呀

### ISSUE THREAD

**Issue by pfchu** [HengY1Sky/Jxx-Stuhealth#2]

**Comment by HengY1Sky** [comment]
Linux上使用是一个道理，只是路径的话更换对应的就好了。

**Comment by HengY1Sky** [comment]
搞了个Docker版本，到对应的分支下即可：👇
https://github.com/HengY1Sky/Jxx-Stuhealth/tree/docker

我将关闭该问题。若还有疑问，请另起Issue。
